// Code generated by go-swagger; DO NOT EDIT.

package quota

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// NewAddQuotaParams creates a new AddQuotaParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddQuotaParams() *AddQuotaParams {
	return &AddQuotaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddQuotaParamsWithTimeout creates a new AddQuotaParams object
// with the ability to set a timeout on a request.
func NewAddQuotaParamsWithTimeout(timeout time.Duration) *AddQuotaParams {
	return &AddQuotaParams{
		timeout: timeout,
	}
}

// NewAddQuotaParamsWithContext creates a new AddQuotaParams object
// with the ability to set a context for a request.
func NewAddQuotaParamsWithContext(ctx context.Context) *AddQuotaParams {
	return &AddQuotaParams{
		Context: ctx,
	}
}

// NewAddQuotaParamsWithHTTPClient creates a new AddQuotaParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddQuotaParamsWithHTTPClient(client *http.Client) *AddQuotaParams {
	return &AddQuotaParams{
		HTTPClient: client,
	}
}

/* AddQuotaParams contains all the parameters to send to the API endpoint
   for the add quota operation.

   Typically these are written to a http.Request.
*/
type AddQuotaParams struct {

	/* Quota.

	   Quota Info
	*/
	Quota *models.Quota

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add quota params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddQuotaParams) WithDefaults() *AddQuotaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add quota params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddQuotaParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add quota params
func (o *AddQuotaParams) WithTimeout(timeout time.Duration) *AddQuotaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add quota params
func (o *AddQuotaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add quota params
func (o *AddQuotaParams) WithContext(ctx context.Context) *AddQuotaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add quota params
func (o *AddQuotaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add quota params
func (o *AddQuotaParams) WithHTTPClient(client *http.Client) *AddQuotaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add quota params
func (o *AddQuotaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithQuota adds the quota to the add quota params
func (o *AddQuotaParams) WithQuota(quota *models.Quota) *AddQuotaParams {
	o.SetQuota(quota)
	return o
}

// SetQuota adds the quota to the add quota params
func (o *AddQuotaParams) SetQuota(quota *models.Quota) {
	o.Quota = quota
}

// WriteToRequest writes these params to a swagger request
func (o *AddQuotaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Quota != nil {
		if err := r.SetBodyParam(o.Quota); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
