// Code generated by go-swagger; DO NOT EDIT.

package quota

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// DeleteQuotaReader is a Reader for the DeleteQuota structure.
type DeleteQuotaReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteQuotaReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteQuotaOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewDeleteQuotaNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteQuotaUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteQuotaForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteQuotaNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteQuotaOK creates a DeleteQuotaOK with default headers values
func NewDeleteQuotaOK() *DeleteQuotaOK {
	return &DeleteQuotaOK{}
}

/* DeleteQuotaOK describes a response with status code 200, with default header values.

Owner deleted
*/
type DeleteQuotaOK struct {
}

func (o *DeleteQuotaOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/quotas/{owner}][%d] deleteQuotaOK ", 200)
}

func (o *DeleteQuotaOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteQuotaNoContent creates a DeleteQuotaNoContent with default headers values
func NewDeleteQuotaNoContent() *DeleteQuotaNoContent {
	return &DeleteQuotaNoContent{}
}

/* DeleteQuotaNoContent describes a response with status code 204, with default header values.

No Content
*/
type DeleteQuotaNoContent struct {
}

func (o *DeleteQuotaNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v1/quotas/{owner}][%d] deleteQuotaNoContent ", 204)
}

func (o *DeleteQuotaNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteQuotaUnauthorized creates a DeleteQuotaUnauthorized with default headers values
func NewDeleteQuotaUnauthorized() *DeleteQuotaUnauthorized {
	return &DeleteQuotaUnauthorized{}
}

/* DeleteQuotaUnauthorized describes a response with status code 401, with default header values.

Authentication failure. Please check credentials and try again.
*/
type DeleteQuotaUnauthorized struct {
}

func (o *DeleteQuotaUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v1/quotas/{owner}][%d] deleteQuotaUnauthorized ", 401)
}

func (o *DeleteQuotaUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteQuotaForbidden creates a DeleteQuotaForbidden with default headers values
func NewDeleteQuotaForbidden() *DeleteQuotaForbidden {
	return &DeleteQuotaForbidden{}
}

/* DeleteQuotaForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteQuotaForbidden struct {
}

func (o *DeleteQuotaForbidden) Error() string {
	return fmt.Sprintf("[DELETE /v1/quotas/{owner}][%d] deleteQuotaForbidden ", 403)
}

func (o *DeleteQuotaForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteQuotaNotFound creates a DeleteQuotaNotFound with default headers values
func NewDeleteQuotaNotFound() *DeleteQuotaNotFound {
	return &DeleteQuotaNotFound{}
}

/* DeleteQuotaNotFound describes a response with status code 404, with default header values.

Owner does not exist
*/
type DeleteQuotaNotFound struct {
	Payload *models.ErrorResponse
}

func (o *DeleteQuotaNotFound) Error() string {
	return fmt.Sprintf("[DELETE /v1/quotas/{owner}][%d] deleteQuotaNotFound  %+v", 404, o.Payload)
}
func (o *DeleteQuotaNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteQuotaNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
