// Code generated by go-swagger; DO NOT EDIT.

package quota

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteQuotaParams creates a new DeleteQuotaParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteQuotaParams() *DeleteQuotaParams {
	return &DeleteQuotaParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteQuotaParamsWithTimeout creates a new DeleteQuotaParams object
// with the ability to set a timeout on a request.
func NewDeleteQuotaParamsWithTimeout(timeout time.Duration) *DeleteQuotaParams {
	return &DeleteQuotaParams{
		timeout: timeout,
	}
}

// NewDeleteQuotaParamsWithContext creates a new DeleteQuotaParams object
// with the ability to set a context for a request.
func NewDeleteQuotaParamsWithContext(ctx context.Context) *DeleteQuotaParams {
	return &DeleteQuotaParams{
		Context: ctx,
	}
}

// NewDeleteQuotaParamsWithHTTPClient creates a new DeleteQuotaParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteQuotaParamsWithHTTPClient(client *http.Client) *DeleteQuotaParams {
	return &DeleteQuotaParams{
		HTTPClient: client,
	}
}

/* DeleteQuotaParams contains all the parameters to send to the API endpoint
   for the delete quota operation.

   Typically these are written to a http.Request.
*/
type DeleteQuotaParams struct {

	/* Owner.

	   The owner name
	*/
	Owner string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete quota params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteQuotaParams) WithDefaults() *DeleteQuotaParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete quota params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteQuotaParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete quota params
func (o *DeleteQuotaParams) WithTimeout(timeout time.Duration) *DeleteQuotaParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete quota params
func (o *DeleteQuotaParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete quota params
func (o *DeleteQuotaParams) WithContext(ctx context.Context) *DeleteQuotaParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete quota params
func (o *DeleteQuotaParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete quota params
func (o *DeleteQuotaParams) WithHTTPClient(client *http.Client) *DeleteQuotaParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete quota params
func (o *DeleteQuotaParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOwner adds the owner to the delete quota params
func (o *DeleteQuotaParams) WithOwner(owner string) *DeleteQuotaParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the delete quota params
func (o *DeleteQuotaParams) SetOwner(owner string) {
	o.Owner = owner
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteQuotaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
