// Code generated by go-swagger; DO NOT EDIT.

package quota

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// ListQuotasReader is a Reader for the ListQuotas structure.
type ListQuotasReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListQuotasReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListQuotasOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListQuotasUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListQuotasForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListQuotasNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListQuotasOK creates a ListQuotasOK with default headers values
func NewListQuotasOK() *ListQuotasOK {
	return &ListQuotasOK{}
}

/* ListQuotasOK describes a response with status code 200, with default header values.

Listed successfully
*/
type ListQuotasOK struct {
	Payload []*models.Quota
}

func (o *ListQuotasOK) Error() string {
	return fmt.Sprintf("[GET /v1/quotas][%d] listQuotasOK  %+v", 200, o.Payload)
}
func (o *ListQuotasOK) GetPayload() []*models.Quota {
	return o.Payload
}

func (o *ListQuotasOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListQuotasUnauthorized creates a ListQuotasUnauthorized with default headers values
func NewListQuotasUnauthorized() *ListQuotasUnauthorized {
	return &ListQuotasUnauthorized{}
}

/* ListQuotasUnauthorized describes a response with status code 401, with default header values.

Authentication failure. Please check credentials and try again.
*/
type ListQuotasUnauthorized struct {
}

func (o *ListQuotasUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/quotas][%d] listQuotasUnauthorized ", 401)
}

func (o *ListQuotasUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListQuotasForbidden creates a ListQuotasForbidden with default headers values
func NewListQuotasForbidden() *ListQuotasForbidden {
	return &ListQuotasForbidden{}
}

/* ListQuotasForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type ListQuotasForbidden struct {
}

func (o *ListQuotasForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/quotas][%d] listQuotasForbidden ", 403)
}

func (o *ListQuotasForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListQuotasNotFound creates a ListQuotasNotFound with default headers values
func NewListQuotasNotFound() *ListQuotasNotFound {
	return &ListQuotasNotFound{}
}

/* ListQuotasNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ListQuotasNotFound struct {
}

func (o *ListQuotasNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/quotas][%d] listQuotasNotFound ", 404)
}

func (o *ListQuotasNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
