// Code generated by go-swagger; DO NOT EDIT.

package data_dictionary_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDictionaryUsingGETParams creates a new GetDictionaryUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDictionaryUsingGETParams() *GetDictionaryUsingGETParams {
	return &GetDictionaryUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDictionaryUsingGETParamsWithTimeout creates a new GetDictionaryUsingGETParams object
// with the ability to set a timeout on a request.
func NewGetDictionaryUsingGETParamsWithTimeout(timeout time.Duration) *GetDictionaryUsingGETParams {
	return &GetDictionaryUsingGETParams{
		timeout: timeout,
	}
}

// NewGetDictionaryUsingGETParamsWithContext creates a new GetDictionaryUsingGETParams object
// with the ability to set a context for a request.
func NewGetDictionaryUsingGETParamsWithContext(ctx context.Context) *GetDictionaryUsingGETParams {
	return &GetDictionaryUsingGETParams{
		Context: ctx,
	}
}

// NewGetDictionaryUsingGETParamsWithHTTPClient creates a new GetDictionaryUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDictionaryUsingGETParamsWithHTTPClient(client *http.Client) *GetDictionaryUsingGETParams {
	return &GetDictionaryUsingGETParams{
		HTTPClient: client,
	}
}

/* GetDictionaryUsingGETParams contains all the parameters to send to the API endpoint
   for the get dictionary using g e t operation.

   Typically these are written to a http.Request.
*/
type GetDictionaryUsingGETParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get dictionary using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDictionaryUsingGETParams) WithDefaults() *GetDictionaryUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get dictionary using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDictionaryUsingGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get dictionary using g e t params
func (o *GetDictionaryUsingGETParams) WithTimeout(timeout time.Duration) *GetDictionaryUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get dictionary using g e t params
func (o *GetDictionaryUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get dictionary using g e t params
func (o *GetDictionaryUsingGETParams) WithContext(ctx context.Context) *GetDictionaryUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get dictionary using g e t params
func (o *GetDictionaryUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get dictionary using g e t params
func (o *GetDictionaryUsingGETParams) WithHTTPClient(client *http.Client) *GetDictionaryUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get dictionary using g e t params
func (o *GetDictionaryUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetDictionaryUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
