// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// NewAddNetworkProfileParams creates a new AddNetworkProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddNetworkProfileParams() *AddNetworkProfileParams {
	return &AddNetworkProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddNetworkProfileParamsWithTimeout creates a new AddNetworkProfileParams object
// with the ability to set a timeout on a request.
func NewAddNetworkProfileParamsWithTimeout(timeout time.Duration) *AddNetworkProfileParams {
	return &AddNetworkProfileParams{
		timeout: timeout,
	}
}

// NewAddNetworkProfileParamsWithContext creates a new AddNetworkProfileParams object
// with the ability to set a context for a request.
func NewAddNetworkProfileParamsWithContext(ctx context.Context) *AddNetworkProfileParams {
	return &AddNetworkProfileParams{
		Context: ctx,
	}
}

// NewAddNetworkProfileParamsWithHTTPClient creates a new AddNetworkProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddNetworkProfileParamsWithHTTPClient(client *http.Client) *AddNetworkProfileParams {
	return &AddNetworkProfileParams{
		HTTPClient: client,
	}
}

/* AddNetworkProfileParams contains all the parameters to send to the API endpoint
   for the add network profile operation.

   Typically these are written to a http.Request.
*/
type AddNetworkProfileParams struct {

	/* NetworkProfileRequest.

	   Network profile info
	*/
	NetworkProfileRequest *models.NetworkProfileRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add network profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddNetworkProfileParams) WithDefaults() *AddNetworkProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add network profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddNetworkProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add network profile params
func (o *AddNetworkProfileParams) WithTimeout(timeout time.Duration) *AddNetworkProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add network profile params
func (o *AddNetworkProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add network profile params
func (o *AddNetworkProfileParams) WithContext(ctx context.Context) *AddNetworkProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add network profile params
func (o *AddNetworkProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add network profile params
func (o *AddNetworkProfileParams) WithHTTPClient(client *http.Client) *AddNetworkProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add network profile params
func (o *AddNetworkProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithNetworkProfileRequest adds the networkProfileRequest to the add network profile params
func (o *AddNetworkProfileParams) WithNetworkProfileRequest(networkProfileRequest *models.NetworkProfileRequest) *AddNetworkProfileParams {
	o.SetNetworkProfileRequest(networkProfileRequest)
	return o
}

// SetNetworkProfileRequest adds the networkProfileRequest to the add network profile params
func (o *AddNetworkProfileParams) SetNetworkProfileRequest(networkProfileRequest *models.NetworkProfileRequest) {
	o.NetworkProfileRequest = networkProfileRequest
}

// WriteToRequest writes these params to a swagger request
func (o *AddNetworkProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.NetworkProfileRequest != nil {
		if err := r.SetBodyParam(o.NetworkProfileRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
