// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// NewAddKubernetesProfileParams creates a new AddKubernetesProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddKubernetesProfileParams() *AddKubernetesProfileParams {
	return &AddKubernetesProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddKubernetesProfileParamsWithTimeout creates a new AddKubernetesProfileParams object
// with the ability to set a timeout on a request.
func NewAddKubernetesProfileParamsWithTimeout(timeout time.Duration) *AddKubernetesProfileParams {
	return &AddKubernetesProfileParams{
		timeout: timeout,
	}
}

// NewAddKubernetesProfileParamsWithContext creates a new AddKubernetesProfileParams object
// with the ability to set a context for a request.
func NewAddKubernetesProfileParamsWithContext(ctx context.Context) *AddKubernetesProfileParams {
	return &AddKubernetesProfileParams{
		Context: ctx,
	}
}

// NewAddKubernetesProfileParamsWithHTTPClient creates a new AddKubernetesProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddKubernetesProfileParamsWithHTTPClient(client *http.Client) *AddKubernetesProfileParams {
	return &AddKubernetesProfileParams{
		HTTPClient: client,
	}
}

/* AddKubernetesProfileParams contains all the parameters to send to the API endpoint
   for the add kubernetes profile operation.

   Typically these are written to a http.Request.
*/
type AddKubernetesProfileParams struct {

	/* KubernetesProfileRequest.

	   Kubernetes profile info
	*/
	KubernetesProfileRequest *models.KubernetesProfileRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add kubernetes profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddKubernetesProfileParams) WithDefaults() *AddKubernetesProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add kubernetes profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddKubernetesProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add kubernetes profile params
func (o *AddKubernetesProfileParams) WithTimeout(timeout time.Duration) *AddKubernetesProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add kubernetes profile params
func (o *AddKubernetesProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add kubernetes profile params
func (o *AddKubernetesProfileParams) WithContext(ctx context.Context) *AddKubernetesProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add kubernetes profile params
func (o *AddKubernetesProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add kubernetes profile params
func (o *AddKubernetesProfileParams) WithHTTPClient(client *http.Client) *AddKubernetesProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add kubernetes profile params
func (o *AddKubernetesProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithKubernetesProfileRequest adds the kubernetesProfileRequest to the add kubernetes profile params
func (o *AddKubernetesProfileParams) WithKubernetesProfileRequest(kubernetesProfileRequest *models.KubernetesProfileRequest) *AddKubernetesProfileParams {
	o.SetKubernetesProfileRequest(kubernetesProfileRequest)
	return o
}

// SetKubernetesProfileRequest adds the kubernetesProfileRequest to the add kubernetes profile params
func (o *AddKubernetesProfileParams) SetKubernetesProfileRequest(kubernetesProfileRequest *models.KubernetesProfileRequest) {
	o.KubernetesProfileRequest = kubernetesProfileRequest
}

// WriteToRequest writes these params to a swagger request
func (o *AddKubernetesProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.KubernetesProfileRequest != nil {
		if err := r.SetBodyParam(o.KubernetesProfileRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
