// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// NewAddComputeProfileParams creates a new AddComputeProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddComputeProfileParams() *AddComputeProfileParams {
	return &AddComputeProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddComputeProfileParamsWithTimeout creates a new AddComputeProfileParams object
// with the ability to set a timeout on a request.
func NewAddComputeProfileParamsWithTimeout(timeout time.Duration) *AddComputeProfileParams {
	return &AddComputeProfileParams{
		timeout: timeout,
	}
}

// NewAddComputeProfileParamsWithContext creates a new AddComputeProfileParams object
// with the ability to set a context for a request.
func NewAddComputeProfileParamsWithContext(ctx context.Context) *AddComputeProfileParams {
	return &AddComputeProfileParams{
		Context: ctx,
	}
}

// NewAddComputeProfileParamsWithHTTPClient creates a new AddComputeProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddComputeProfileParamsWithHTTPClient(client *http.Client) *AddComputeProfileParams {
	return &AddComputeProfileParams{
		HTTPClient: client,
	}
}

/* AddComputeProfileParams contains all the parameters to send to the API endpoint
   for the add compute profile operation.

   Typically these are written to a http.Request.
*/
type AddComputeProfileParams struct {

	/* ComputeProfileRequest.

	   Compute profile info
	*/
	ComputeProfileRequest *models.ComputeProfileRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add compute profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddComputeProfileParams) WithDefaults() *AddComputeProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add compute profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddComputeProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add compute profile params
func (o *AddComputeProfileParams) WithTimeout(timeout time.Duration) *AddComputeProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add compute profile params
func (o *AddComputeProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add compute profile params
func (o *AddComputeProfileParams) WithContext(ctx context.Context) *AddComputeProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add compute profile params
func (o *AddComputeProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add compute profile params
func (o *AddComputeProfileParams) WithHTTPClient(client *http.Client) *AddComputeProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add compute profile params
func (o *AddComputeProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithComputeProfileRequest adds the computeProfileRequest to the add compute profile params
func (o *AddComputeProfileParams) WithComputeProfileRequest(computeProfileRequest *models.ComputeProfileRequest) *AddComputeProfileParams {
	o.SetComputeProfileRequest(computeProfileRequest)
	return o
}

// SetComputeProfileRequest adds the computeProfileRequest to the add compute profile params
func (o *AddComputeProfileParams) SetComputeProfileRequest(computeProfileRequest *models.ComputeProfileRequest) {
	o.ComputeProfileRequest = computeProfileRequest
}

// WriteToRequest writes these params to a swagger request
func (o *AddComputeProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.ComputeProfileRequest != nil {
		if err := r.SetBodyParam(o.ComputeProfileRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
