// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// AddNetworkProfileReader is a Reader for the AddNetworkProfile structure.
type AddNetworkProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddNetworkProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddNetworkProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewAddNetworkProfileCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddNetworkProfileBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAddNetworkProfileUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAddNetworkProfileForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAddNetworkProfileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewAddNetworkProfileMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewAddNetworkProfileConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewAddNetworkProfileUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddNetworkProfileOK creates a AddNetworkProfileOK with default headers values
func NewAddNetworkProfileOK() *AddNetworkProfileOK {
	return &AddNetworkProfileOK{}
}

/* AddNetworkProfileOK describes a response with status code 200, with default header values.

OK
*/
type AddNetworkProfileOK struct {
}

func (o *AddNetworkProfileOK) Error() string {
	return fmt.Sprintf("[POST /v1/network-profiles][%d] addNetworkProfileOK ", 200)
}

func (o *AddNetworkProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddNetworkProfileCreated creates a AddNetworkProfileCreated with default headers values
func NewAddNetworkProfileCreated() *AddNetworkProfileCreated {
	return &AddNetworkProfileCreated{}
}

/* AddNetworkProfileCreated describes a response with status code 201, with default header values.

Successful operation
*/
type AddNetworkProfileCreated struct {
}

func (o *AddNetworkProfileCreated) Error() string {
	return fmt.Sprintf("[POST /v1/network-profiles][%d] addNetworkProfileCreated ", 201)
}

func (o *AddNetworkProfileCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddNetworkProfileBadRequest creates a AddNetworkProfileBadRequest with default headers values
func NewAddNetworkProfileBadRequest() *AddNetworkProfileBadRequest {
	return &AddNetworkProfileBadRequest{}
}

/* AddNetworkProfileBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type AddNetworkProfileBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *AddNetworkProfileBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/network-profiles][%d] addNetworkProfileBadRequest  %+v", 400, o.Payload)
}
func (o *AddNetworkProfileBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *AddNetworkProfileBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddNetworkProfileUnauthorized creates a AddNetworkProfileUnauthorized with default headers values
func NewAddNetworkProfileUnauthorized() *AddNetworkProfileUnauthorized {
	return &AddNetworkProfileUnauthorized{}
}

/* AddNetworkProfileUnauthorized describes a response with status code 401, with default header values.

Authentication failure. Please check credentials and try again.
*/
type AddNetworkProfileUnauthorized struct {
}

func (o *AddNetworkProfileUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/network-profiles][%d] addNetworkProfileUnauthorized ", 401)
}

func (o *AddNetworkProfileUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddNetworkProfileForbidden creates a AddNetworkProfileForbidden with default headers values
func NewAddNetworkProfileForbidden() *AddNetworkProfileForbidden {
	return &AddNetworkProfileForbidden{}
}

/* AddNetworkProfileForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type AddNetworkProfileForbidden struct {
}

func (o *AddNetworkProfileForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/network-profiles][%d] addNetworkProfileForbidden ", 403)
}

func (o *AddNetworkProfileForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddNetworkProfileNotFound creates a AddNetworkProfileNotFound with default headers values
func NewAddNetworkProfileNotFound() *AddNetworkProfileNotFound {
	return &AddNetworkProfileNotFound{}
}

/* AddNetworkProfileNotFound describes a response with status code 404, with default header values.

Not Found
*/
type AddNetworkProfileNotFound struct {
}

func (o *AddNetworkProfileNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/network-profiles][%d] addNetworkProfileNotFound ", 404)
}

func (o *AddNetworkProfileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddNetworkProfileMethodNotAllowed creates a AddNetworkProfileMethodNotAllowed with default headers values
func NewAddNetworkProfileMethodNotAllowed() *AddNetworkProfileMethodNotAllowed {
	return &AddNetworkProfileMethodNotAllowed{}
}

/* AddNetworkProfileMethodNotAllowed describes a response with status code 405, with default header values.

Invalid input
*/
type AddNetworkProfileMethodNotAllowed struct {
}

func (o *AddNetworkProfileMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /v1/network-profiles][%d] addNetworkProfileMethodNotAllowed ", 405)
}

func (o *AddNetworkProfileMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddNetworkProfileConflict creates a AddNetworkProfileConflict with default headers values
func NewAddNetworkProfileConflict() *AddNetworkProfileConflict {
	return &AddNetworkProfileConflict{}
}

/* AddNetworkProfileConflict describes a response with status code 409, with default header values.

Network profile with that name already exists
*/
type AddNetworkProfileConflict struct {
	Payload *models.ErrorResponse
}

func (o *AddNetworkProfileConflict) Error() string {
	return fmt.Sprintf("[POST /v1/network-profiles][%d] addNetworkProfileConflict  %+v", 409, o.Payload)
}
func (o *AddNetworkProfileConflict) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *AddNetworkProfileConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddNetworkProfileUnprocessableEntity creates a AddNetworkProfileUnprocessableEntity with default headers values
func NewAddNetworkProfileUnprocessableEntity() *AddNetworkProfileUnprocessableEntity {
	return &AddNetworkProfileUnprocessableEntity{}
}

/* AddNetworkProfileUnprocessableEntity describes a response with status code 422, with default header values.

Error adding network profile
*/
type AddNetworkProfileUnprocessableEntity struct {
	Payload *models.ErrorResponse
}

func (o *AddNetworkProfileUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /v1/network-profiles][%d] addNetworkProfileUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *AddNetworkProfileUnprocessableEntity) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *AddNetworkProfileUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
