// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// AddKubernetesProfileReader is a Reader for the AddKubernetesProfile structure.
type AddKubernetesProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AddKubernetesProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAddKubernetesProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 201:
		result := NewAddKubernetesProfileCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAddKubernetesProfileBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAddKubernetesProfileUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewAddKubernetesProfileForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewAddKubernetesProfileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 405:
		result := NewAddKubernetesProfileMethodNotAllowed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewAddKubernetesProfileConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewAddKubernetesProfileUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAddKubernetesProfileOK creates a AddKubernetesProfileOK with default headers values
func NewAddKubernetesProfileOK() *AddKubernetesProfileOK {
	return &AddKubernetesProfileOK{}
}

/* AddKubernetesProfileOK describes a response with status code 200, with default header values.

OK
*/
type AddKubernetesProfileOK struct {
}

func (o *AddKubernetesProfileOK) Error() string {
	return fmt.Sprintf("[POST /v1/kubernetes-profiles][%d] addKubernetesProfileOK ", 200)
}

func (o *AddKubernetesProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddKubernetesProfileCreated creates a AddKubernetesProfileCreated with default headers values
func NewAddKubernetesProfileCreated() *AddKubernetesProfileCreated {
	return &AddKubernetesProfileCreated{}
}

/* AddKubernetesProfileCreated describes a response with status code 201, with default header values.

Successful operation
*/
type AddKubernetesProfileCreated struct {
}

func (o *AddKubernetesProfileCreated) Error() string {
	return fmt.Sprintf("[POST /v1/kubernetes-profiles][%d] addKubernetesProfileCreated ", 201)
}

func (o *AddKubernetesProfileCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddKubernetesProfileBadRequest creates a AddKubernetesProfileBadRequest with default headers values
func NewAddKubernetesProfileBadRequest() *AddKubernetesProfileBadRequest {
	return &AddKubernetesProfileBadRequest{}
}

/* AddKubernetesProfileBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type AddKubernetesProfileBadRequest struct {
	Payload *models.ErrorResponse
}

func (o *AddKubernetesProfileBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1/kubernetes-profiles][%d] addKubernetesProfileBadRequest  %+v", 400, o.Payload)
}
func (o *AddKubernetesProfileBadRequest) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *AddKubernetesProfileBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddKubernetesProfileUnauthorized creates a AddKubernetesProfileUnauthorized with default headers values
func NewAddKubernetesProfileUnauthorized() *AddKubernetesProfileUnauthorized {
	return &AddKubernetesProfileUnauthorized{}
}

/* AddKubernetesProfileUnauthorized describes a response with status code 401, with default header values.

Authentication failure. Please check credentials and try again.
*/
type AddKubernetesProfileUnauthorized struct {
}

func (o *AddKubernetesProfileUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1/kubernetes-profiles][%d] addKubernetesProfileUnauthorized ", 401)
}

func (o *AddKubernetesProfileUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddKubernetesProfileForbidden creates a AddKubernetesProfileForbidden with default headers values
func NewAddKubernetesProfileForbidden() *AddKubernetesProfileForbidden {
	return &AddKubernetesProfileForbidden{}
}

/* AddKubernetesProfileForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type AddKubernetesProfileForbidden struct {
}

func (o *AddKubernetesProfileForbidden) Error() string {
	return fmt.Sprintf("[POST /v1/kubernetes-profiles][%d] addKubernetesProfileForbidden ", 403)
}

func (o *AddKubernetesProfileForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddKubernetesProfileNotFound creates a AddKubernetesProfileNotFound with default headers values
func NewAddKubernetesProfileNotFound() *AddKubernetesProfileNotFound {
	return &AddKubernetesProfileNotFound{}
}

/* AddKubernetesProfileNotFound describes a response with status code 404, with default header values.

Not Found
*/
type AddKubernetesProfileNotFound struct {
}

func (o *AddKubernetesProfileNotFound) Error() string {
	return fmt.Sprintf("[POST /v1/kubernetes-profiles][%d] addKubernetesProfileNotFound ", 404)
}

func (o *AddKubernetesProfileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddKubernetesProfileMethodNotAllowed creates a AddKubernetesProfileMethodNotAllowed with default headers values
func NewAddKubernetesProfileMethodNotAllowed() *AddKubernetesProfileMethodNotAllowed {
	return &AddKubernetesProfileMethodNotAllowed{}
}

/* AddKubernetesProfileMethodNotAllowed describes a response with status code 405, with default header values.

Invalid input
*/
type AddKubernetesProfileMethodNotAllowed struct {
}

func (o *AddKubernetesProfileMethodNotAllowed) Error() string {
	return fmt.Sprintf("[POST /v1/kubernetes-profiles][%d] addKubernetesProfileMethodNotAllowed ", 405)
}

func (o *AddKubernetesProfileMethodNotAllowed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAddKubernetesProfileConflict creates a AddKubernetesProfileConflict with default headers values
func NewAddKubernetesProfileConflict() *AddKubernetesProfileConflict {
	return &AddKubernetesProfileConflict{}
}

/* AddKubernetesProfileConflict describes a response with status code 409, with default header values.

Kubernetes profile with that name already exists
*/
type AddKubernetesProfileConflict struct {
	Payload *models.ErrorResponse
}

func (o *AddKubernetesProfileConflict) Error() string {
	return fmt.Sprintf("[POST /v1/kubernetes-profiles][%d] addKubernetesProfileConflict  %+v", 409, o.Payload)
}
func (o *AddKubernetesProfileConflict) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *AddKubernetesProfileConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAddKubernetesProfileUnprocessableEntity creates a AddKubernetesProfileUnprocessableEntity with default headers values
func NewAddKubernetesProfileUnprocessableEntity() *AddKubernetesProfileUnprocessableEntity {
	return &AddKubernetesProfileUnprocessableEntity{}
}

/* AddKubernetesProfileUnprocessableEntity describes a response with status code 422, with default header values.

Error adding kubernetes profile
*/
type AddKubernetesProfileUnprocessableEntity struct {
	Payload *models.ErrorResponse
}

func (o *AddKubernetesProfileUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /v1/kubernetes-profiles][%d] addKubernetesProfileUnprocessableEntity  %+v", 422, o.Payload)
}
func (o *AddKubernetesProfileUnprocessableEntity) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *AddKubernetesProfileUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
