// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// DeleteKubernetesProfileReader is a Reader for the DeleteKubernetesProfile structure.
type DeleteKubernetesProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteKubernetesProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteKubernetesProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewDeleteKubernetesProfileNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteKubernetesProfileUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteKubernetesProfileForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteKubernetesProfileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteKubernetesProfileOK creates a DeleteKubernetesProfileOK with default headers values
func NewDeleteKubernetesProfileOK() *DeleteKubernetesProfileOK {
	return &DeleteKubernetesProfileOK{}
}

/* DeleteKubernetesProfileOK describes a response with status code 200, with default header values.

OK
*/
type DeleteKubernetesProfileOK struct {
}

func (o *DeleteKubernetesProfileOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/kubernetes-profiles/{name}][%d] deleteKubernetesProfileOK ", 200)
}

func (o *DeleteKubernetesProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteKubernetesProfileNoContent creates a DeleteKubernetesProfileNoContent with default headers values
func NewDeleteKubernetesProfileNoContent() *DeleteKubernetesProfileNoContent {
	return &DeleteKubernetesProfileNoContent{}
}

/* DeleteKubernetesProfileNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type DeleteKubernetesProfileNoContent struct {
}

func (o *DeleteKubernetesProfileNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v1/kubernetes-profiles/{name}][%d] deleteKubernetesProfileNoContent ", 204)
}

func (o *DeleteKubernetesProfileNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteKubernetesProfileUnauthorized creates a DeleteKubernetesProfileUnauthorized with default headers values
func NewDeleteKubernetesProfileUnauthorized() *DeleteKubernetesProfileUnauthorized {
	return &DeleteKubernetesProfileUnauthorized{}
}

/* DeleteKubernetesProfileUnauthorized describes a response with status code 401, with default header values.

Authentication failure. Please check credentials and try again.
*/
type DeleteKubernetesProfileUnauthorized struct {
}

func (o *DeleteKubernetesProfileUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v1/kubernetes-profiles/{name}][%d] deleteKubernetesProfileUnauthorized ", 401)
}

func (o *DeleteKubernetesProfileUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteKubernetesProfileForbidden creates a DeleteKubernetesProfileForbidden with default headers values
func NewDeleteKubernetesProfileForbidden() *DeleteKubernetesProfileForbidden {
	return &DeleteKubernetesProfileForbidden{}
}

/* DeleteKubernetesProfileForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteKubernetesProfileForbidden struct {
}

func (o *DeleteKubernetesProfileForbidden) Error() string {
	return fmt.Sprintf("[DELETE /v1/kubernetes-profiles/{name}][%d] deleteKubernetesProfileForbidden ", 403)
}

func (o *DeleteKubernetesProfileForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteKubernetesProfileNotFound creates a DeleteKubernetesProfileNotFound with default headers values
func NewDeleteKubernetesProfileNotFound() *DeleteKubernetesProfileNotFound {
	return &DeleteKubernetesProfileNotFound{}
}

/* DeleteKubernetesProfileNotFound describes a response with status code 404, with default header values.

The network profile does not exist
*/
type DeleteKubernetesProfileNotFound struct {
	Payload *models.ErrorResponse
}

func (o *DeleteKubernetesProfileNotFound) Error() string {
	return fmt.Sprintf("[DELETE /v1/kubernetes-profiles/{name}][%d] deleteKubernetesProfileNotFound  %+v", 404, o.Payload)
}
func (o *DeleteKubernetesProfileNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteKubernetesProfileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
