// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// DeleteNetworkProfileReader is a Reader for the DeleteNetworkProfile structure.
type DeleteNetworkProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteNetworkProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteNetworkProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewDeleteNetworkProfileNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteNetworkProfileUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteNetworkProfileForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteNetworkProfileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteNetworkProfileOK creates a DeleteNetworkProfileOK with default headers values
func NewDeleteNetworkProfileOK() *DeleteNetworkProfileOK {
	return &DeleteNetworkProfileOK{}
}

/* DeleteNetworkProfileOK describes a response with status code 200, with default header values.

OK
*/
type DeleteNetworkProfileOK struct {
}

func (o *DeleteNetworkProfileOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/network-profiles/{profileName}][%d] deleteNetworkProfileOK ", 200)
}

func (o *DeleteNetworkProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteNetworkProfileNoContent creates a DeleteNetworkProfileNoContent with default headers values
func NewDeleteNetworkProfileNoContent() *DeleteNetworkProfileNoContent {
	return &DeleteNetworkProfileNoContent{}
}

/* DeleteNetworkProfileNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type DeleteNetworkProfileNoContent struct {
}

func (o *DeleteNetworkProfileNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v1/network-profiles/{profileName}][%d] deleteNetworkProfileNoContent ", 204)
}

func (o *DeleteNetworkProfileNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteNetworkProfileUnauthorized creates a DeleteNetworkProfileUnauthorized with default headers values
func NewDeleteNetworkProfileUnauthorized() *DeleteNetworkProfileUnauthorized {
	return &DeleteNetworkProfileUnauthorized{}
}

/* DeleteNetworkProfileUnauthorized describes a response with status code 401, with default header values.

Authentication failure. Please check credentials and try again.
*/
type DeleteNetworkProfileUnauthorized struct {
}

func (o *DeleteNetworkProfileUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v1/network-profiles/{profileName}][%d] deleteNetworkProfileUnauthorized ", 401)
}

func (o *DeleteNetworkProfileUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteNetworkProfileForbidden creates a DeleteNetworkProfileForbidden with default headers values
func NewDeleteNetworkProfileForbidden() *DeleteNetworkProfileForbidden {
	return &DeleteNetworkProfileForbidden{}
}

/* DeleteNetworkProfileForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteNetworkProfileForbidden struct {
}

func (o *DeleteNetworkProfileForbidden) Error() string {
	return fmt.Sprintf("[DELETE /v1/network-profiles/{profileName}][%d] deleteNetworkProfileForbidden ", 403)
}

func (o *DeleteNetworkProfileForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteNetworkProfileNotFound creates a DeleteNetworkProfileNotFound with default headers values
func NewDeleteNetworkProfileNotFound() *DeleteNetworkProfileNotFound {
	return &DeleteNetworkProfileNotFound{}
}

/* DeleteNetworkProfileNotFound describes a response with status code 404, with default header values.

The network profile does not exist
*/
type DeleteNetworkProfileNotFound struct {
	Payload *models.ErrorResponse
}

func (o *DeleteNetworkProfileNotFound) Error() string {
	return fmt.Sprintf("[DELETE /v1/network-profiles/{profileName}][%d] deleteNetworkProfileNotFound  %+v", 404, o.Payload)
}
func (o *DeleteNetworkProfileNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteNetworkProfileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
