// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// DeleteComputeProfileReader is a Reader for the DeleteComputeProfile structure.
type DeleteComputeProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteComputeProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteComputeProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 204:
		result := NewDeleteComputeProfileNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteComputeProfileUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteComputeProfileForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteComputeProfileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteComputeProfileOK creates a DeleteComputeProfileOK with default headers values
func NewDeleteComputeProfileOK() *DeleteComputeProfileOK {
	return &DeleteComputeProfileOK{}
}

/* DeleteComputeProfileOK describes a response with status code 200, with default header values.

OK
*/
type DeleteComputeProfileOK struct {
}

func (o *DeleteComputeProfileOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/compute-profiles/{profileName}][%d] deleteComputeProfileOK ", 200)
}

func (o *DeleteComputeProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteComputeProfileNoContent creates a DeleteComputeProfileNoContent with default headers values
func NewDeleteComputeProfileNoContent() *DeleteComputeProfileNoContent {
	return &DeleteComputeProfileNoContent{}
}

/* DeleteComputeProfileNoContent describes a response with status code 204, with default header values.

Successful operation
*/
type DeleteComputeProfileNoContent struct {
}

func (o *DeleteComputeProfileNoContent) Error() string {
	return fmt.Sprintf("[DELETE /v1/compute-profiles/{profileName}][%d] deleteComputeProfileNoContent ", 204)
}

func (o *DeleteComputeProfileNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteComputeProfileUnauthorized creates a DeleteComputeProfileUnauthorized with default headers values
func NewDeleteComputeProfileUnauthorized() *DeleteComputeProfileUnauthorized {
	return &DeleteComputeProfileUnauthorized{}
}

/* DeleteComputeProfileUnauthorized describes a response with status code 401, with default header values.

Authentication failure. Please check credentials and try again.
*/
type DeleteComputeProfileUnauthorized struct {
}

func (o *DeleteComputeProfileUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /v1/compute-profiles/{profileName}][%d] deleteComputeProfileUnauthorized ", 401)
}

func (o *DeleteComputeProfileUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteComputeProfileForbidden creates a DeleteComputeProfileForbidden with default headers values
func NewDeleteComputeProfileForbidden() *DeleteComputeProfileForbidden {
	return &DeleteComputeProfileForbidden{}
}

/* DeleteComputeProfileForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type DeleteComputeProfileForbidden struct {
}

func (o *DeleteComputeProfileForbidden) Error() string {
	return fmt.Sprintf("[DELETE /v1/compute-profiles/{profileName}][%d] deleteComputeProfileForbidden ", 403)
}

func (o *DeleteComputeProfileForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteComputeProfileNotFound creates a DeleteComputeProfileNotFound with default headers values
func NewDeleteComputeProfileNotFound() *DeleteComputeProfileNotFound {
	return &DeleteComputeProfileNotFound{}
}

/* DeleteComputeProfileNotFound describes a response with status code 404, with default header values.

The compute profile does not exist
*/
type DeleteComputeProfileNotFound struct {
	Payload *models.ErrorResponse
}

func (o *DeleteComputeProfileNotFound) Error() string {
	return fmt.Sprintf("[DELETE /v1/compute-profiles/{profileName}][%d] deleteComputeProfileNotFound  %+v", 404, o.Payload)
}
func (o *DeleteComputeProfileNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteComputeProfileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
