// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// GetKubernetesProfileReader is a Reader for the GetKubernetesProfile structure.
type GetKubernetesProfileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetKubernetesProfileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetKubernetesProfileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetKubernetesProfileUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetKubernetesProfileForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetKubernetesProfileNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetKubernetesProfileOK creates a GetKubernetesProfileOK with default headers values
func NewGetKubernetesProfileOK() *GetKubernetesProfileOK {
	return &GetKubernetesProfileOK{}
}

/* GetKubernetesProfileOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetKubernetesProfileOK struct {
	Payload *models.KubernetesProfile
}

func (o *GetKubernetesProfileOK) Error() string {
	return fmt.Sprintf("[GET /v1/kubernetes-profiles/{name}][%d] getKubernetesProfileOK  %+v", 200, o.Payload)
}
func (o *GetKubernetesProfileOK) GetPayload() *models.KubernetesProfile {
	return o.Payload
}

func (o *GetKubernetesProfileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.KubernetesProfile)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetKubernetesProfileUnauthorized creates a GetKubernetesProfileUnauthorized with default headers values
func NewGetKubernetesProfileUnauthorized() *GetKubernetesProfileUnauthorized {
	return &GetKubernetesProfileUnauthorized{}
}

/* GetKubernetesProfileUnauthorized describes a response with status code 401, with default header values.

Authentication failure. Please check credentials and try again.
*/
type GetKubernetesProfileUnauthorized struct {
}

func (o *GetKubernetesProfileUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/kubernetes-profiles/{name}][%d] getKubernetesProfileUnauthorized ", 401)
}

func (o *GetKubernetesProfileUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetKubernetesProfileForbidden creates a GetKubernetesProfileForbidden with default headers values
func NewGetKubernetesProfileForbidden() *GetKubernetesProfileForbidden {
	return &GetKubernetesProfileForbidden{}
}

/* GetKubernetesProfileForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetKubernetesProfileForbidden struct {
}

func (o *GetKubernetesProfileForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/kubernetes-profiles/{name}][%d] getKubernetesProfileForbidden ", 403)
}

func (o *GetKubernetesProfileForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetKubernetesProfileNotFound creates a GetKubernetesProfileNotFound with default headers values
func NewGetKubernetesProfileNotFound() *GetKubernetesProfileNotFound {
	return &GetKubernetesProfileNotFound{}
}

/* GetKubernetesProfileNotFound describes a response with status code 404, with default header values.

Network profile does not exist
*/
type GetKubernetesProfileNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetKubernetesProfileNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/kubernetes-profiles/{name}][%d] getKubernetesProfileNotFound  %+v", 404, o.Payload)
}
func (o *GetKubernetesProfileNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetKubernetesProfileNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
