// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetComputeProfileParams creates a new GetComputeProfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetComputeProfileParams() *GetComputeProfileParams {
	return &GetComputeProfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetComputeProfileParamsWithTimeout creates a new GetComputeProfileParams object
// with the ability to set a timeout on a request.
func NewGetComputeProfileParamsWithTimeout(timeout time.Duration) *GetComputeProfileParams {
	return &GetComputeProfileParams{
		timeout: timeout,
	}
}

// NewGetComputeProfileParamsWithContext creates a new GetComputeProfileParams object
// with the ability to set a context for a request.
func NewGetComputeProfileParamsWithContext(ctx context.Context) *GetComputeProfileParams {
	return &GetComputeProfileParams{
		Context: ctx,
	}
}

// NewGetComputeProfileParamsWithHTTPClient creates a new GetComputeProfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetComputeProfileParamsWithHTTPClient(client *http.Client) *GetComputeProfileParams {
	return &GetComputeProfileParams{
		HTTPClient: client,
	}
}

/* GetComputeProfileParams contains all the parameters to send to the API endpoint
   for the get compute profile operation.

   Typically these are written to a http.Request.
*/
type GetComputeProfileParams struct {

	/* ProfileName.

	   The compute profile name
	*/
	ProfileName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get compute profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetComputeProfileParams) WithDefaults() *GetComputeProfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get compute profile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetComputeProfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get compute profile params
func (o *GetComputeProfileParams) WithTimeout(timeout time.Duration) *GetComputeProfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get compute profile params
func (o *GetComputeProfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get compute profile params
func (o *GetComputeProfileParams) WithContext(ctx context.Context) *GetComputeProfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get compute profile params
func (o *GetComputeProfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get compute profile params
func (o *GetComputeProfileParams) WithHTTPClient(client *http.Client) *GetComputeProfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get compute profile params
func (o *GetComputeProfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProfileName adds the profileName to the get compute profile params
func (o *GetComputeProfileParams) WithProfileName(profileName string) *GetComputeProfileParams {
	o.SetProfileName(profileName)
	return o
}

// SetProfileName adds the profileName to the get compute profile params
func (o *GetComputeProfileParams) SetProfileName(profileName string) {
	o.ProfileName = profileName
}

// WriteToRequest writes these params to a swagger request
func (o *GetComputeProfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param profileName
	if err := r.SetPathParam("profileName", o.ProfileName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
