// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// ListNetworkProfilesReader is a Reader for the ListNetworkProfiles structure.
type ListNetworkProfilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListNetworkProfilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListNetworkProfilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListNetworkProfilesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListNetworkProfilesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListNetworkProfilesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListNetworkProfilesOK creates a ListNetworkProfilesOK with default headers values
func NewListNetworkProfilesOK() *ListNetworkProfilesOK {
	return &ListNetworkProfilesOK{}
}

/* ListNetworkProfilesOK describes a response with status code 200, with default header values.

Listed successfully
*/
type ListNetworkProfilesOK struct {
	Payload []*models.NetworkProfile
}

func (o *ListNetworkProfilesOK) Error() string {
	return fmt.Sprintf("[GET /v1/network-profiles][%d] listNetworkProfilesOK  %+v", 200, o.Payload)
}
func (o *ListNetworkProfilesOK) GetPayload() []*models.NetworkProfile {
	return o.Payload
}

func (o *ListNetworkProfilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListNetworkProfilesUnauthorized creates a ListNetworkProfilesUnauthorized with default headers values
func NewListNetworkProfilesUnauthorized() *ListNetworkProfilesUnauthorized {
	return &ListNetworkProfilesUnauthorized{}
}

/* ListNetworkProfilesUnauthorized describes a response with status code 401, with default header values.

Authentication failure. Please check credentials and try again.
*/
type ListNetworkProfilesUnauthorized struct {
}

func (o *ListNetworkProfilesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/network-profiles][%d] listNetworkProfilesUnauthorized ", 401)
}

func (o *ListNetworkProfilesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListNetworkProfilesForbidden creates a ListNetworkProfilesForbidden with default headers values
func NewListNetworkProfilesForbidden() *ListNetworkProfilesForbidden {
	return &ListNetworkProfilesForbidden{}
}

/* ListNetworkProfilesForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type ListNetworkProfilesForbidden struct {
}

func (o *ListNetworkProfilesForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/network-profiles][%d] listNetworkProfilesForbidden ", 403)
}

func (o *ListNetworkProfilesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListNetworkProfilesNotFound creates a ListNetworkProfilesNotFound with default headers values
func NewListNetworkProfilesNotFound() *ListNetworkProfilesNotFound {
	return &ListNetworkProfilesNotFound{}
}

/* ListNetworkProfilesNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ListNetworkProfilesNotFound struct {
}

func (o *ListNetworkProfilesNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/network-profiles][%d] listNetworkProfilesNotFound ", 404)
}

func (o *ListNetworkProfilesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
