// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListNetworkProfilesParams creates a new ListNetworkProfilesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListNetworkProfilesParams() *ListNetworkProfilesParams {
	return &ListNetworkProfilesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListNetworkProfilesParamsWithTimeout creates a new ListNetworkProfilesParams object
// with the ability to set a timeout on a request.
func NewListNetworkProfilesParamsWithTimeout(timeout time.Duration) *ListNetworkProfilesParams {
	return &ListNetworkProfilesParams{
		timeout: timeout,
	}
}

// NewListNetworkProfilesParamsWithContext creates a new ListNetworkProfilesParams object
// with the ability to set a context for a request.
func NewListNetworkProfilesParamsWithContext(ctx context.Context) *ListNetworkProfilesParams {
	return &ListNetworkProfilesParams{
		Context: ctx,
	}
}

// NewListNetworkProfilesParamsWithHTTPClient creates a new ListNetworkProfilesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListNetworkProfilesParamsWithHTTPClient(client *http.Client) *ListNetworkProfilesParams {
	return &ListNetworkProfilesParams{
		HTTPClient: client,
	}
}

/* ListNetworkProfilesParams contains all the parameters to send to the API endpoint
   for the list network profiles operation.

   Typically these are written to a http.Request.
*/
type ListNetworkProfilesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list network profiles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListNetworkProfilesParams) WithDefaults() *ListNetworkProfilesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list network profiles params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListNetworkProfilesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list network profiles params
func (o *ListNetworkProfilesParams) WithTimeout(timeout time.Duration) *ListNetworkProfilesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list network profiles params
func (o *ListNetworkProfilesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list network profiles params
func (o *ListNetworkProfilesParams) WithContext(ctx context.Context) *ListNetworkProfilesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list network profiles params
func (o *ListNetworkProfilesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list network profiles params
func (o *ListNetworkProfilesParams) WithHTTPClient(client *http.Client) *ListNetworkProfilesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list network profiles params
func (o *ListNetworkProfilesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListNetworkProfilesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
