// Code generated by go-swagger; DO NOT EDIT.

package profile

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// ListKubernetesProfilesReader is a Reader for the ListKubernetesProfiles structure.
type ListKubernetesProfilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListKubernetesProfilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListKubernetesProfilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListKubernetesProfilesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListKubernetesProfilesForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListKubernetesProfilesNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListKubernetesProfilesOK creates a ListKubernetesProfilesOK with default headers values
func NewListKubernetesProfilesOK() *ListKubernetesProfilesOK {
	return &ListKubernetesProfilesOK{}
}

/* ListKubernetesProfilesOK describes a response with status code 200, with default header values.

Listed successfully
*/
type ListKubernetesProfilesOK struct {
	Payload []*models.KubernetesProfile
}

func (o *ListKubernetesProfilesOK) Error() string {
	return fmt.Sprintf("[GET /v1/kubernetes-profiles][%d] listKubernetesProfilesOK  %+v", 200, o.Payload)
}
func (o *ListKubernetesProfilesOK) GetPayload() []*models.KubernetesProfile {
	return o.Payload
}

func (o *ListKubernetesProfilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListKubernetesProfilesUnauthorized creates a ListKubernetesProfilesUnauthorized with default headers values
func NewListKubernetesProfilesUnauthorized() *ListKubernetesProfilesUnauthorized {
	return &ListKubernetesProfilesUnauthorized{}
}

/* ListKubernetesProfilesUnauthorized describes a response with status code 401, with default header values.

Authentication failure. Please check credentials and try again.
*/
type ListKubernetesProfilesUnauthorized struct {
}

func (o *ListKubernetesProfilesUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/kubernetes-profiles][%d] listKubernetesProfilesUnauthorized ", 401)
}

func (o *ListKubernetesProfilesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListKubernetesProfilesForbidden creates a ListKubernetesProfilesForbidden with default headers values
func NewListKubernetesProfilesForbidden() *ListKubernetesProfilesForbidden {
	return &ListKubernetesProfilesForbidden{}
}

/* ListKubernetesProfilesForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type ListKubernetesProfilesForbidden struct {
}

func (o *ListKubernetesProfilesForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/kubernetes-profiles][%d] listKubernetesProfilesForbidden ", 403)
}

func (o *ListKubernetesProfilesForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListKubernetesProfilesNotFound creates a ListKubernetesProfilesNotFound with default headers values
func NewListKubernetesProfilesNotFound() *ListKubernetesProfilesNotFound {
	return &ListKubernetesProfilesNotFound{}
}

/* ListKubernetesProfilesNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ListKubernetesProfilesNotFound struct {
}

func (o *ListKubernetesProfilesNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/kubernetes-profiles][%d] listKubernetesProfilesNotFound ", 404)
}

func (o *ListKubernetesProfilesNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
