// Code generated by go-swagger; DO NOT EDIT.

package basic_error_controller

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewErrorUsingPUTParams creates a new ErrorUsingPUTParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewErrorUsingPUTParams() *ErrorUsingPUTParams {
	return &ErrorUsingPUTParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewErrorUsingPUTParamsWithTimeout creates a new ErrorUsingPUTParams object
// with the ability to set a timeout on a request.
func NewErrorUsingPUTParamsWithTimeout(timeout time.Duration) *ErrorUsingPUTParams {
	return &ErrorUsingPUTParams{
		timeout: timeout,
	}
}

// NewErrorUsingPUTParamsWithContext creates a new ErrorUsingPUTParams object
// with the ability to set a context for a request.
func NewErrorUsingPUTParamsWithContext(ctx context.Context) *ErrorUsingPUTParams {
	return &ErrorUsingPUTParams{
		Context: ctx,
	}
}

// NewErrorUsingPUTParamsWithHTTPClient creates a new ErrorUsingPUTParams object
// with the ability to set a custom HTTPClient for a request.
func NewErrorUsingPUTParamsWithHTTPClient(client *http.Client) *ErrorUsingPUTParams {
	return &ErrorUsingPUTParams{
		HTTPClient: client,
	}
}

/* ErrorUsingPUTParams contains all the parameters to send to the API endpoint
   for the error using p u t operation.

   Typically these are written to a http.Request.
*/
type ErrorUsingPUTParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the error using p u t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ErrorUsingPUTParams) WithDefaults() *ErrorUsingPUTParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the error using p u t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ErrorUsingPUTParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the error using p u t params
func (o *ErrorUsingPUTParams) WithTimeout(timeout time.Duration) *ErrorUsingPUTParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the error using p u t params
func (o *ErrorUsingPUTParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the error using p u t params
func (o *ErrorUsingPUTParams) WithContext(ctx context.Context) *ErrorUsingPUTParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the error using p u t params
func (o *ErrorUsingPUTParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the error using p u t params
func (o *ErrorUsingPUTParams) WithHTTPClient(client *http.Client) *ErrorUsingPUTParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the error using p u t params
func (o *ErrorUsingPUTParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ErrorUsingPUTParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
