// Code generated by go-swagger; DO NOT EDIT.

package upgradable

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewCheckUpgradableParams creates a new CheckUpgradableParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewCheckUpgradableParams() *CheckUpgradableParams {
	return &CheckUpgradableParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCheckUpgradableParamsWithTimeout creates a new CheckUpgradableParams object
// with the ability to set a timeout on a request.
func NewCheckUpgradableParamsWithTimeout(timeout time.Duration) *CheckUpgradableParams {
	return &CheckUpgradableParams{
		timeout: timeout,
	}
}

// NewCheckUpgradableParamsWithContext creates a new CheckUpgradableParams object
// with the ability to set a context for a request.
func NewCheckUpgradableParamsWithContext(ctx context.Context) *CheckUpgradableParams {
	return &CheckUpgradableParams{
		Context: ctx,
	}
}

// NewCheckUpgradableParamsWithHTTPClient creates a new CheckUpgradableParams object
// with the ability to set a custom HTTPClient for a request.
func NewCheckUpgradableParamsWithHTTPClient(client *http.Client) *CheckUpgradableParams {
	return &CheckUpgradableParams{
		HTTPClient: client,
	}
}

/* CheckUpgradableParams contains all the parameters to send to the API endpoint
   for the check upgradable operation.

   Typically these are written to a http.Request.
*/
type CheckUpgradableParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the check upgradable params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CheckUpgradableParams) WithDefaults() *CheckUpgradableParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the check upgradable params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *CheckUpgradableParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the check upgradable params
func (o *CheckUpgradableParams) WithTimeout(timeout time.Duration) *CheckUpgradableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the check upgradable params
func (o *CheckUpgradableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the check upgradable params
func (o *CheckUpgradableParams) WithContext(ctx context.Context) *CheckUpgradableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the check upgradable params
func (o *CheckUpgradableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the check upgradable params
func (o *CheckUpgradableParams) WithHTTPClient(client *http.Client) *CheckUpgradableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the check upgradable params
func (o *CheckUpgradableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *CheckUpgradableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
