// Code generated by go-swagger; DO NOT EDIT.

package web_mvc_links_handler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewLinksUsingGETParams creates a new LinksUsingGETParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewLinksUsingGETParams() *LinksUsingGETParams {
	return &LinksUsingGETParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewLinksUsingGETParamsWithTimeout creates a new LinksUsingGETParams object
// with the ability to set a timeout on a request.
func NewLinksUsingGETParamsWithTimeout(timeout time.Duration) *LinksUsingGETParams {
	return &LinksUsingGETParams{
		timeout: timeout,
	}
}

// NewLinksUsingGETParamsWithContext creates a new LinksUsingGETParams object
// with the ability to set a context for a request.
func NewLinksUsingGETParamsWithContext(ctx context.Context) *LinksUsingGETParams {
	return &LinksUsingGETParams{
		Context: ctx,
	}
}

// NewLinksUsingGETParamsWithHTTPClient creates a new LinksUsingGETParams object
// with the ability to set a custom HTTPClient for a request.
func NewLinksUsingGETParamsWithHTTPClient(client *http.Client) *LinksUsingGETParams {
	return &LinksUsingGETParams{
		HTTPClient: client,
	}
}

/* LinksUsingGETParams contains all the parameters to send to the API endpoint
   for the links using g e t operation.

   Typically these are written to a http.Request.
*/
type LinksUsingGETParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the links using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LinksUsingGETParams) WithDefaults() *LinksUsingGETParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the links using g e t params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *LinksUsingGETParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the links using g e t params
func (o *LinksUsingGETParams) WithTimeout(timeout time.Duration) *LinksUsingGETParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the links using g e t params
func (o *LinksUsingGETParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the links using g e t params
func (o *LinksUsingGETParams) WithContext(ctx context.Context) *LinksUsingGETParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the links using g e t params
func (o *LinksUsingGETParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the links using g e t params
func (o *LinksUsingGETParams) WithHTTPClient(client *http.Client) *LinksUsingGETParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the links using g e t params
func (o *LinksUsingGETParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *LinksUsingGETParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
