// Code generated by go-swagger; DO NOT EDIT.

package plans

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// ListPlansReader is a Reader for the ListPlans structure.
type ListPlansReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListPlansReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListPlansOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListPlansUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewListPlansForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListPlansNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListPlansOK creates a ListPlansOK with default headers values
func NewListPlansOK() *ListPlansOK {
	return &ListPlansOK{}
}

/* ListPlansOK describes a response with status code 200, with default header values.

List of plans retrieved successfully
*/
type ListPlansOK struct {
	Payload []*models.Plan
}

func (o *ListPlansOK) Error() string {
	return fmt.Sprintf("[GET /v1/plans][%d] listPlansOK  %+v", 200, o.Payload)
}
func (o *ListPlansOK) GetPayload() []*models.Plan {
	return o.Payload
}

func (o *ListPlansOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListPlansUnauthorized creates a ListPlansUnauthorized with default headers values
func NewListPlansUnauthorized() *ListPlansUnauthorized {
	return &ListPlansUnauthorized{}
}

/* ListPlansUnauthorized describes a response with status code 401, with default header values.

Authentication failure. Please check credentials and try again.
*/
type ListPlansUnauthorized struct {
}

func (o *ListPlansUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/plans][%d] listPlansUnauthorized ", 401)
}

func (o *ListPlansUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListPlansForbidden creates a ListPlansForbidden with default headers values
func NewListPlansForbidden() *ListPlansForbidden {
	return &ListPlansForbidden{}
}

/* ListPlansForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type ListPlansForbidden struct {
}

func (o *ListPlansForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/plans][%d] listPlansForbidden ", 403)
}

func (o *ListPlansForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewListPlansNotFound creates a ListPlansNotFound with default headers values
func NewListPlansNotFound() *ListPlansNotFound {
	return &ListPlansNotFound{}
}

/* ListPlansNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ListPlansNotFound struct {
}

func (o *ListPlansNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/plans][%d] listPlansNotFound ", 404)
}

func (o *ListPlansNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
