// Code generated by go-swagger; DO NOT EDIT.

package usage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// GetUsageReader is a Reader for the GetUsage structure.
type GetUsageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetUsageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetUsageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetUsageUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetUsageForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetUsageNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetUsageOK creates a GetUsageOK with default headers values
func NewGetUsageOK() *GetUsageOK {
	return &GetUsageOK{}
}

/* GetUsageOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetUsageOK struct {
	Payload *models.Usage
}

func (o *GetUsageOK) Error() string {
	return fmt.Sprintf("[GET /v1/usages/{owner}][%d] getUsageOK  %+v", 200, o.Payload)
}
func (o *GetUsageOK) GetPayload() *models.Usage {
	return o.Payload
}

func (o *GetUsageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Usage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetUsageUnauthorized creates a GetUsageUnauthorized with default headers values
func NewGetUsageUnauthorized() *GetUsageUnauthorized {
	return &GetUsageUnauthorized{}
}

/* GetUsageUnauthorized describes a response with status code 401, with default header values.

Authentication failure. Please check credentials and try again.
*/
type GetUsageUnauthorized struct {
}

func (o *GetUsageUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/usages/{owner}][%d] getUsageUnauthorized ", 401)
}

func (o *GetUsageUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetUsageForbidden creates a GetUsageForbidden with default headers values
func NewGetUsageForbidden() *GetUsageForbidden {
	return &GetUsageForbidden{}
}

/* GetUsageForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetUsageForbidden struct {
}

func (o *GetUsageForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/usages/{owner}][%d] getUsageForbidden ", 403)
}

func (o *GetUsageForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetUsageNotFound creates a GetUsageNotFound with default headers values
func NewGetUsageNotFound() *GetUsageNotFound {
	return &GetUsageNotFound{}
}

/* GetUsageNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetUsageNotFound struct {
}

func (o *GetUsageNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/usages/{owner}][%d] getUsageNotFound ", 404)
}

func (o *GetUsageNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
