// Code generated by go-swagger; DO NOT EDIT.

package usage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListUsagesParams creates a new ListUsagesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListUsagesParams() *ListUsagesParams {
	return &ListUsagesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListUsagesParamsWithTimeout creates a new ListUsagesParams object
// with the ability to set a timeout on a request.
func NewListUsagesParamsWithTimeout(timeout time.Duration) *ListUsagesParams {
	return &ListUsagesParams{
		timeout: timeout,
	}
}

// NewListUsagesParamsWithContext creates a new ListUsagesParams object
// with the ability to set a context for a request.
func NewListUsagesParamsWithContext(ctx context.Context) *ListUsagesParams {
	return &ListUsagesParams{
		Context: ctx,
	}
}

// NewListUsagesParamsWithHTTPClient creates a new ListUsagesParams object
// with the ability to set a custom HTTPClient for a request.
func NewListUsagesParamsWithHTTPClient(client *http.Client) *ListUsagesParams {
	return &ListUsagesParams{
		HTTPClient: client,
	}
}

/* ListUsagesParams contains all the parameters to send to the API endpoint
   for the list usages operation.

   Typically these are written to a http.Request.
*/
type ListUsagesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list usages params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListUsagesParams) WithDefaults() *ListUsagesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list usages params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListUsagesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list usages params
func (o *ListUsagesParams) WithTimeout(timeout time.Duration) *ListUsagesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list usages params
func (o *ListUsagesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list usages params
func (o *ListUsagesParams) WithContext(ctx context.Context) *ListUsagesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list usages params
func (o *ListUsagesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list usages params
func (o *ListUsagesParams) WithHTTPClient(client *http.Client) *ListUsagesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list usages params
func (o *ListUsagesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListUsagesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
