// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// GetClusterDetailsReader is a Reader for the GetClusterDetails structure.
type GetClusterDetailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetClusterDetailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetClusterDetailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetClusterDetailsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetClusterDetailsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetClusterDetailsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetClusterDetailsOK creates a GetClusterDetailsOK with default headers values
func NewGetClusterDetailsOK() *GetClusterDetailsOK {
	return &GetClusterDetailsOK{}
}

/* GetClusterDetailsOK describes a response with status code 200, with default header values.

Successful operation
*/
type GetClusterDetailsOK struct {
	Payload *models.Cluster
}

func (o *GetClusterDetailsOK) Error() string {
	return fmt.Sprintf("[GET /v1/clusterdetails/{clusterName}][%d] getClusterDetailsOK  %+v", 200, o.Payload)
}
func (o *GetClusterDetailsOK) GetPayload() *models.Cluster {
	return o.Payload
}

func (o *GetClusterDetailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Cluster)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetClusterDetailsUnauthorized creates a GetClusterDetailsUnauthorized with default headers values
func NewGetClusterDetailsUnauthorized() *GetClusterDetailsUnauthorized {
	return &GetClusterDetailsUnauthorized{}
}

/* GetClusterDetailsUnauthorized describes a response with status code 401, with default header values.

Authentication failure. Please check credentials and try again.
*/
type GetClusterDetailsUnauthorized struct {
}

func (o *GetClusterDetailsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1/clusterdetails/{clusterName}][%d] getClusterDetailsUnauthorized ", 401)
}

func (o *GetClusterDetailsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetClusterDetailsForbidden creates a GetClusterDetailsForbidden with default headers values
func NewGetClusterDetailsForbidden() *GetClusterDetailsForbidden {
	return &GetClusterDetailsForbidden{}
}

/* GetClusterDetailsForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type GetClusterDetailsForbidden struct {
}

func (o *GetClusterDetailsForbidden) Error() string {
	return fmt.Sprintf("[GET /v1/clusterdetails/{clusterName}][%d] getClusterDetailsForbidden ", 403)
}

func (o *GetClusterDetailsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetClusterDetailsNotFound creates a GetClusterDetailsNotFound with default headers values
func NewGetClusterDetailsNotFound() *GetClusterDetailsNotFound {
	return &GetClusterDetailsNotFound{}
}

/* GetClusterDetailsNotFound describes a response with status code 404, with default header values.

Cluster does not exist
*/
type GetClusterDetailsNotFound struct {
	Payload *models.ErrorResponse
}

func (o *GetClusterDetailsNotFound) Error() string {
	return fmt.Sprintf("[GET /v1/clusterdetails/{clusterName}][%d] getClusterDetailsNotFound  %+v", 404, o.Payload)
}
func (o *GetClusterDetailsNotFound) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetClusterDetailsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
