// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetClusterDetailsParams creates a new GetClusterDetailsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetClusterDetailsParams() *GetClusterDetailsParams {
	return &GetClusterDetailsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetClusterDetailsParamsWithTimeout creates a new GetClusterDetailsParams object
// with the ability to set a timeout on a request.
func NewGetClusterDetailsParamsWithTimeout(timeout time.Duration) *GetClusterDetailsParams {
	return &GetClusterDetailsParams{
		timeout: timeout,
	}
}

// NewGetClusterDetailsParamsWithContext creates a new GetClusterDetailsParams object
// with the ability to set a context for a request.
func NewGetClusterDetailsParamsWithContext(ctx context.Context) *GetClusterDetailsParams {
	return &GetClusterDetailsParams{
		Context: ctx,
	}
}

// NewGetClusterDetailsParamsWithHTTPClient creates a new GetClusterDetailsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetClusterDetailsParamsWithHTTPClient(client *http.Client) *GetClusterDetailsParams {
	return &GetClusterDetailsParams{
		HTTPClient: client,
	}
}

/* GetClusterDetailsParams contains all the parameters to send to the API endpoint
   for the get cluster details operation.

   Typically these are written to a http.Request.
*/
type GetClusterDetailsParams struct {

	/* ClusterName.

	   The cluster name
	*/
	ClusterName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get cluster details params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClusterDetailsParams) WithDefaults() *GetClusterDetailsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get cluster details params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetClusterDetailsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get cluster details params
func (o *GetClusterDetailsParams) WithTimeout(timeout time.Duration) *GetClusterDetailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get cluster details params
func (o *GetClusterDetailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get cluster details params
func (o *GetClusterDetailsParams) WithContext(ctx context.Context) *GetClusterDetailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get cluster details params
func (o *GetClusterDetailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get cluster details params
func (o *GetClusterDetailsParams) WithHTTPClient(client *http.Client) *GetClusterDetailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get cluster details params
func (o *GetClusterDetailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterName adds the clusterName to the get cluster details params
func (o *GetClusterDetailsParams) WithClusterName(clusterName string) *GetClusterDetailsParams {
	o.SetClusterName(clusterName)
	return o
}

// SetClusterName adds the clusterName to the get cluster details params
func (o *GetClusterDetailsParams) SetClusterName(clusterName string) {
	o.ClusterName = clusterName
}

// WriteToRequest writes these params to a swagger request
func (o *GetClusterDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param clusterName
	if err := r.SetPathParam("clusterName", o.ClusterName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
