// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/uempfel/tkgi-client-go/models"
)

// NewUpgradeClustersParams creates a new UpgradeClustersParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewUpgradeClustersParams() *UpgradeClustersParams {
	return &UpgradeClustersParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewUpgradeClustersParamsWithTimeout creates a new UpgradeClustersParams object
// with the ability to set a timeout on a request.
func NewUpgradeClustersParamsWithTimeout(timeout time.Duration) *UpgradeClustersParams {
	return &UpgradeClustersParams{
		timeout: timeout,
	}
}

// NewUpgradeClustersParamsWithContext creates a new UpgradeClustersParams object
// with the ability to set a context for a request.
func NewUpgradeClustersParamsWithContext(ctx context.Context) *UpgradeClustersParams {
	return &UpgradeClustersParams{
		Context: ctx,
	}
}

// NewUpgradeClustersParamsWithHTTPClient creates a new UpgradeClustersParams object
// with the ability to set a custom HTTPClient for a request.
func NewUpgradeClustersParamsWithHTTPClient(client *http.Client) *UpgradeClustersParams {
	return &UpgradeClustersParams{
		HTTPClient: client,
	}
}

/* UpgradeClustersParams contains all the parameters to send to the API endpoint
   for the upgrade clusters operation.

   Typically these are written to a http.Request.
*/
type UpgradeClustersParams struct {

	/* Body.

	   Cluster info
	*/
	Body *models.UpgradeClustersRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the upgrade clusters params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpgradeClustersParams) WithDefaults() *UpgradeClustersParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the upgrade clusters params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *UpgradeClustersParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the upgrade clusters params
func (o *UpgradeClustersParams) WithTimeout(timeout time.Duration) *UpgradeClustersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upgrade clusters params
func (o *UpgradeClustersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the upgrade clusters params
func (o *UpgradeClustersParams) WithContext(ctx context.Context) *UpgradeClustersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upgrade clusters params
func (o *UpgradeClustersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the upgrade clusters params
func (o *UpgradeClustersParams) WithHTTPClient(client *http.Client) *UpgradeClustersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the upgrade clusters params
func (o *UpgradeClustersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the upgrade clusters params
func (o *UpgradeClustersParams) WithBody(body *models.UpgradeClustersRequest) *UpgradeClustersParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the upgrade clusters params
func (o *UpgradeClustersParams) SetBody(body *models.UpgradeClustersRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UpgradeClustersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
