// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AZ AZ
//
// swagger:model AZ
type AZ struct {

	// cloud properties
	// Required: true
	CloudProperties interface{} `json:"cloud_properties"`

	// cpi
	// Required: true
	Cpi *string `json:"cpi"`

	// name
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this a z
func (m *AZ) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCloudProperties(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCpi(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AZ) validateCloudProperties(formats strfmt.Registry) error {

	if m.CloudProperties == nil {
		return errors.Required("cloud_properties", "body", nil)
	}

	return nil
}

func (m *AZ) validateCpi(formats strfmt.Registry) error {

	if err := validate.Required("cpi", "body", m.Cpi); err != nil {
		return err
	}

	return nil
}

func (m *AZ) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this a z based on context it is used
func (m *AZ) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AZ) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AZ) UnmarshalBinary(b []byte) error {
	var res AZ
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
