// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AvailableClusterUpgrade AvailableClusterUpgrade
//
// swagger:model AvailableClusterUpgrade
type AvailableClusterUpgrade struct {

	// component
	Component string `json:"component,omitempty"`

	// version
	Version string `json:"version,omitempty"`
}

// Validate validates this available cluster upgrade
func (m *AvailableClusterUpgrade) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this available cluster upgrade based on context it is used
func (m *AvailableClusterUpgrade) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AvailableClusterUpgrade) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AvailableClusterUpgrade) UnmarshalBinary(b []byte) error {
	var res AvailableClusterUpgrade
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
