// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ClusterCertificate ClusterCertificate
//
// swagger:model ClusterCertificate
type ClusterCertificate struct {

	// The flag indicates ca certificates
	Ca bool `json:"ca,omitempty"`

	// The expiry time of certificate
	ExpiryTime string `json:"expiry_time,omitempty"`

	// The uuid of a certificate
	ID string `json:"id,omitempty"`

	// The name of the certificate
	Name string `json:"name,omitempty"`

	// The uuid of current version of certificate
	VersionID string `json:"version_id,omitempty"`
}

// Validate validates this cluster certificate
func (m *ClusterCertificate) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this cluster certificate based on context it is used
func (m *ClusterCertificate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ClusterCertificate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ClusterCertificate) UnmarshalBinary(b []byte) error {
	var res ClusterCertificate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
