// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CustomCaCert CustomCaCert
//
// swagger:model CustomCaCert
type CustomCaCert struct {

	// ca cert
	CaCert string `json:"ca_cert,omitempty"`

	// Domain name allows [a-zA-Z0-9_] in surroundings and [-.] in the middle. It also allows port in the end.
	DomainName string `json:"domain_name,omitempty"`
}

// Validate validates this custom ca cert
func (m *CustomCaCert) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this custom ca cert based on context it is used
func (m *CustomCaCert) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CustomCaCert) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustomCaCert) UnmarshalBinary(b []byte) error {
	var res CustomCaCert
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
