// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// KubernetesSettings KubernetesSettings
//
// swagger:model KubernetesSettings
type KubernetesSettings struct {

	// kubelet drain delete local data
	KubeletDrainDeleteLocalData string `json:"kubelet_drain_delete_local_data,omitempty"`

	// kubelet drain force
	KubeletDrainForce string `json:"kubelet_drain_force,omitempty"`

	// kubelet drain force node
	KubeletDrainForceNode string `json:"kubelet_drain_force_node,omitempty"`

	// kubelet drain grace period
	KubeletDrainGracePeriod string `json:"kubelet_drain_grace_period,omitempty"`

	// kubelet drain ignore daemonsets
	KubeletDrainIgnoreDaemonsets string `json:"kubelet_drain_ignore_daemonsets,omitempty"`

	// kubelet drain timeout
	KubeletDrainTimeout string `json:"kubelet_drain_timeout,omitempty"`
}

// Validate validates this kubernetes settings
func (m *KubernetesSettings) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this kubernetes settings based on context it is used
func (m *KubernetesSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KubernetesSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KubernetesSettings) UnmarshalBinary(b []byte) error {
	var res KubernetesSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
