// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// KubernetesCustomizationParameters KubernetesCustomizationParameters
//
// swagger:model KubernetesCustomizationParameters
type KubernetesCustomizationParameters struct {

	// insecure registries
	InsecureRegistries []string `json:"insecure_registries"`

	// unset http proxy
	UnsetHTTPProxy []string `json:"unset_http_proxy"`

	// vsphere cloud provider config key
	VsphereCloudProviderConfigKey string `json:"vsphere_cloud_provider_config_key,omitempty"`
}

// Validate validates this kubernetes customization parameters
func (m *KubernetesCustomizationParameters) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this kubernetes customization parameters based on context it is used
func (m *KubernetesCustomizationParameters) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KubernetesCustomizationParameters) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KubernetesCustomizationParameters) UnmarshalBinary(b []byte) error {
	var res KubernetesCustomizationParameters
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
