// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// KubernetesProfileRequest KubernetesProfileRequest
//
// swagger:model KubernetesProfileRequest
type KubernetesProfileRequest struct {

	// customizations
	Customizations []*KubernetesComponentCustomization `json:"customizations"`

	// description
	Description string `json:"description,omitempty"`

	// experimental customizations
	ExperimentalCustomizations []*KubernetesComponentCustomization `json:"experimental_customizations"`

	// name
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this kubernetes profile request
func (m *KubernetesProfileRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCustomizations(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExperimentalCustomizations(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KubernetesProfileRequest) validateCustomizations(formats strfmt.Registry) error {
	if swag.IsZero(m.Customizations) { // not required
		return nil
	}

	for i := 0; i < len(m.Customizations); i++ {
		if swag.IsZero(m.Customizations[i]) { // not required
			continue
		}

		if m.Customizations[i] != nil {
			if err := m.Customizations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("customizations" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("customizations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *KubernetesProfileRequest) validateExperimentalCustomizations(formats strfmt.Registry) error {
	if swag.IsZero(m.ExperimentalCustomizations) { // not required
		return nil
	}

	for i := 0; i < len(m.ExperimentalCustomizations); i++ {
		if swag.IsZero(m.ExperimentalCustomizations[i]) { // not required
			continue
		}

		if m.ExperimentalCustomizations[i] != nil {
			if err := m.ExperimentalCustomizations[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("experimental_customizations" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("experimental_customizations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *KubernetesProfileRequest) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this kubernetes profile request based on the context it is used
func (m *KubernetesProfileRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCustomizations(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExperimentalCustomizations(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KubernetesProfileRequest) contextValidateCustomizations(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Customizations); i++ {

		if m.Customizations[i] != nil {
			if err := m.Customizations[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("customizations" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("customizations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *KubernetesProfileRequest) contextValidateExperimentalCustomizations(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.ExperimentalCustomizations); i++ {

		if m.ExperimentalCustomizations[i] != nil {
			if err := m.ExperimentalCustomizations[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("experimental_customizations" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("experimental_customizations" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *KubernetesProfileRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KubernetesProfileRequest) UnmarshalBinary(b []byte) error {
	var res KubernetesProfileRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
