// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// KubernetesComponentCustomization KubernetesComponentCustomization
//
// swagger:model KubernetesComponentCustomization
type KubernetesComponentCustomization struct {

	// arguments
	Arguments map[string]string `json:"arguments,omitempty"`

	// component
	// Required: true
	Component *string `json:"component"`

	// file arguments
	FileArguments map[string]string `json:"file-arguments,omitempty"`
}

// Validate validates this kubernetes component customization
func (m *KubernetesComponentCustomization) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateComponent(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *KubernetesComponentCustomization) validateComponent(formats strfmt.Registry) error {

	if err := validate.Required("component", "body", m.Component); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this kubernetes component customization based on context it is used
func (m *KubernetesComponentCustomization) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *KubernetesComponentCustomization) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *KubernetesComponentCustomization) UnmarshalBinary(b []byte) error {
	var res KubernetesComponentCustomization
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
