// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NetPermission NetPermission
//
// swagger:model NetPermission
type NetPermission struct {

	// IP range or IP subnet to which these restrictions will be levied upon
	Ips string `json:"ips,omitempty"`

	// Name of the NetPermission object
	Name string `json:"name,omitempty"`

	// Can either be "READ_WRITE", "READ_ONLY" or "NO_ACCESS"
	Permissions string `json:"permissions,omitempty"`

	// Security access level for the file share volume.
	Rootsquash bool `json:"rootsquash,omitempty"`
}

// Validate validates this net permission
func (m *NetPermission) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this net permission based on context it is used
func (m *NetPermission) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *NetPermission) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *NetPermission) UnmarshalBinary(b []byte) error {
	var res NetPermission
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
