// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// UpgradeClustersRequest UpgradeClustersRequest
//
// swagger:model UpgradeClustersRequest
type UpgradeClustersRequest struct {

	// canaries
	Canaries []string `json:"canaries"`

	// clusters
	Clusters []string `json:"clusters"`

	// max in flight
	MaxInFlight int32 `json:"max_in_flight,omitempty"`
}

// Validate validates this upgrade clusters request
func (m *UpgradeClustersRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this upgrade clusters request based on context it is used
func (m *UpgradeClustersRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpgradeClustersRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpgradeClustersRequest) UnmarshalBinary(b []byte) error {
	var res UpgradeClustersRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
