// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// VMResource VMResource
//
// swagger:model VMResource
type VMResource struct {

	// az names
	AzNames []string `json:"az_names"`

	// cpu
	CPU int32 `json:"cpu,omitempty"`

	// ephemeral disk in mb
	EphemeralDiskInMb int32 `json:"ephemeral_disk_in_mb,omitempty"`

	// instances
	Instances int32 `json:"instances,omitempty"`

	// max worker instances
	MaxWorkerInstances int32 `json:"max_worker_instances,omitempty"`

	// memory in mb
	MemoryInMb int32 `json:"memory_in_mb,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// node labels
	NodeLabels string `json:"node_labels,omitempty"`

	// node taints
	NodeTaints string `json:"node_taints,omitempty"`

	// persistent disk in mb
	PersistentDiskInMb int32 `json:"persistent_disk_in_mb,omitempty"`
}

// Validate validates this VM resource
func (m *VMResource) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this VM resource based on context it is used
func (m *VMResource) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VMResource) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VMResource) UnmarshalBinary(b []byte) error {
	var res VMResource
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
